version: '3.9'

services:
  zookeeper-worker:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper-worker
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    networks:
      internal-net:

  kafka-worker:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-worker
    depends_on:
      - zookeeper-worker
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-worker:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    networks:
      internal-net:

networks:
  internal-net:
    name: internal-net
