issuer: https://oidc.c4-soft.com/auth/realms/rest-showcase
bidule-api-port: 8081
machin-api-port: 8082

server:
  port: ${machin-api-port}
  ssl:
    enabled: false

spring:
  application:
    name: bidule-api
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${issuer}
          principal-claim-name: preferred_username

logging:
  level:
    org:
      springframework:
        security: DEBUG
---
spring:
    config:
        activate:
            on-profile: ssl
server:
  ssl:
    enabled: true
    key-store: classpath:/localhost.p12
    key-store-password: secret